// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tour.Heroes.Api;

namespace Tour.Heroes.Api.Migrations
{
    [DbContext(typeof(HeroDbContext))]
    [Migration("20190219104901_InitializeDatabase")]
    partial class InitializeDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Tour.Heroes.Api.Models.Entities.Ability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreateAt");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<DateTimeOffset>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Abilities");

                    b.HasData(
                        new { Id = new Guid("208da2a6-fcda-4857-aaf4-23bd8b14229d"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 765, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "Specialized in combat", Name = "Martial Arts", UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 765, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("d9f54e4d-a218-4ac4-9572-2545d61adda8"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "Speaks for itself", Name = "Super strength", UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("14cde9b8-045f-473d-92c6-2d9d2ad1930b"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "Super fast for its opponent, but for it feels normal for the speedster", Name = "Super speed", UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("adbacf3a-37a1-4211-9ffb-97b4b898c8e8"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "Specialized with a sword", Name = "Swordsmaster", UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("2f738fd1-a400-420b-b360-009e9bfccbef"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "Speaks for itself", Name = "Marmot de graaf", UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("18c9b872-5865-4279-9ffc-108d23b956df"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "Super fast for its opponent, but for it feels normal for the speedster", Name = "harinak", UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("0004be42-cb00-4f3d-9f4c-f69bc3b46ebb"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "Specialized with a sword", Name = "haha", UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("632c7c6f-16ff-498f-bbe1-bbe0f037f4d7"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "Overthrows his opponent with spells", Name = "Magic", UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) }
                    );
                });

            modelBuilder.Entity("Tour.Heroes.Api.Models.Entities.LinkEntities.MetaHumanAbility", b =>
                {
                    b.Property<Guid>("MetaHumanId");

                    b.Property<Guid>("AbilityId");

                    b.Property<DateTimeOffset>("CreateAt");

                    b.Property<DateTimeOffset>("UpdatedAt");

                    b.HasKey("MetaHumanId", "AbilityId");

                    b.HasIndex("AbilityId");

                    b.ToTable("MetahumansAbilities");

                    b.HasData(
                        new { MetaHumanId = new Guid("87f2ad97-b3a2-4996-9f93-fb756feeb374"), AbilityId = new Guid("208da2a6-fcda-4857-aaf4-23bd8b14229d"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("07488ec0-9066-46bb-bef9-53151b278de6"), AbilityId = new Guid("d9f54e4d-a218-4ac4-9572-2545d61adda8"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 767, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 767, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("7abbc069-155f-4399-a0fa-fb519b731824"), AbilityId = new Guid("adbacf3a-37a1-4211-9ffb-97b4b898c8e8"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 767, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 767, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("21ecf9ee-4fbd-4689-8251-2d6797c3acbe"), AbilityId = new Guid("14cde9b8-045f-473d-92c6-2d9d2ad1930b"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 767, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 767, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("d478bc91-5c51-4438-80bc-891f420a2d06"), AbilityId = new Guid("14cde9b8-045f-473d-92c6-2d9d2ad1930b"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 767, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 767, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("7abbc069-155f-4399-a0fa-fb519b731824"), AbilityId = new Guid("2f738fd1-a400-420b-b360-009e9bfccbef"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 767, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 767, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("d478bc91-5c51-4438-80bc-891f420a2d06"), AbilityId = new Guid("18c9b872-5865-4279-9ffc-108d23b956df"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 767, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 767, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("d478bc91-5c51-4438-80bc-891f420a2d06"), AbilityId = new Guid("0004be42-cb00-4f3d-9f4c-f69bc3b46ebb"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 767, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 767, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("2114c11d-fa71-4f95-8725-90bd699694cf"), AbilityId = new Guid("2f738fd1-a400-420b-b360-009e9bfccbef"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 767, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 767, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("cb0843de-7393-4686-88ea-4c6f80b12a47"), AbilityId = new Guid("d9f54e4d-a218-4ac4-9572-2545d61adda8"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 767, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 767, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("f5c868ae-da99-41ed-96a3-39a85e53fcb3"), AbilityId = new Guid("14cde9b8-045f-473d-92c6-2d9d2ad1930b"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 767, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 767, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("99201ef5-9e88-4f77-b2c9-d55bf844d1b2"), AbilityId = new Guid("208da2a6-fcda-4857-aaf4-23bd8b14229d"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 767, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 767, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("0e4cb48e-fba4-48f1-925c-c396d49ee913"), AbilityId = new Guid("2f738fd1-a400-420b-b360-009e9bfccbef"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 767, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 767, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("442915a0-e192-4cd2-8800-eac1cd034383"), AbilityId = new Guid("632c7c6f-16ff-498f-bbe1-bbe0f037f4d7"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 767, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 767, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("4e9c9def-ca75-4ff2-8fa8-c20e0d4a734a"), AbilityId = new Guid("adbacf3a-37a1-4211-9ffb-97b4b898c8e8"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 767, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 767, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) }
                    );
                });

            modelBuilder.Entity("Tour.Heroes.Api.Models.Entities.LinkEntities.MetaHumanTeam", b =>
                {
                    b.Property<Guid>("MetaHumanId");

                    b.Property<Guid>("TeamId");

                    b.Property<DateTimeOffset>("CreateAt");

                    b.Property<DateTimeOffset>("UpdatedAt");

                    b.HasKey("MetaHumanId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("MetaHumanTeams");

                    b.HasData(
                        new { MetaHumanId = new Guid("2114c11d-fa71-4f95-8725-90bd699694cf"), TeamId = new Guid("d8550cf0-3743-4afa-8530-49a85398cb49"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("cb0843de-7393-4686-88ea-4c6f80b12a47"), TeamId = new Guid("d8550cf0-3743-4afa-8530-49a85398cb49"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("f5c868ae-da99-41ed-96a3-39a85e53fcb3"), TeamId = new Guid("d8550cf0-3743-4afa-8530-49a85398cb49"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("99201ef5-9e88-4f77-b2c9-d55bf844d1b2"), TeamId = new Guid("d8550cf0-3743-4afa-8530-49a85398cb49"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("20b23a0a-242f-4a0f-ad59-93ced35b3cce"), TeamId = new Guid("d8550cf0-3743-4afa-8530-49a85398cb49"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("4746b9f8-ed25-4add-b99c-e4ad1d1e28c6"), TeamId = new Guid("d8550cf0-3743-4afa-8530-49a85398cb49"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("7c19d2b9-d4cf-4182-988d-616b2f308518"), TeamId = new Guid("9ad1b2c3-5276-4b80-9995-ecb8bac1693b"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("b24205f9-43f7-4cf3-a422-1bfc01a1ef0f"), TeamId = new Guid("9ad1b2c3-5276-4b80-9995-ecb8bac1693b"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("ed77765b-0b94-4cf5-bc49-0c6be4f628b6"), TeamId = new Guid("9ad1b2c3-5276-4b80-9995-ecb8bac1693b"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("15d336cc-5318-4031-b80d-680fb2161b9b"), TeamId = new Guid("9ad1b2c3-5276-4b80-9995-ecb8bac1693b"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("3a919c57-c6d4-419b-8d6a-6a0f8596ec14"), TeamId = new Guid("9ad1b2c3-5276-4b80-9995-ecb8bac1693b"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("5c04a440-45a6-4ba3-b31f-fc44777fd20e"), TeamId = new Guid("9ad1b2c3-5276-4b80-9995-ecb8bac1693b"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("d8b9fd4f-d62f-4358-8cf3-a34e43812fa6"), TeamId = new Guid("9ad1b2c3-5276-4b80-9995-ecb8bac1693b"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("cd36b2ef-1ad5-4e36-8968-7d263a7fdae3"), TeamId = new Guid("9ad1b2c3-5276-4b80-9995-ecb8bac1693b"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("37480978-498e-49b0-bc8e-47ac2764b223"), TeamId = new Guid("9ad1b2c3-5276-4b80-9995-ecb8bac1693b"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("d2cd1117-1e96-41e2-9167-7291db001c56"), TeamId = new Guid("9ad1b2c3-5276-4b80-9995-ecb8bac1693b"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) }
                    );
                });

            modelBuilder.Entity("Tour.Heroes.Api.Models.Entities.MetaHuman", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AlterEgo");

                    b.Property<DateTimeOffset>("CreateAt");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int>("Status");

                    b.Property<DateTimeOffset>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Metahumans");

                    b.HasData(
                        new { Id = new Guid("87f2ad97-b3a2-4996-9f93-fb756feeb374"), AlterEgo = "", CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "", Name = "Deathstroke", Status = 1, UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("07488ec0-9066-46bb-bef9-53151b278de6"), AlterEgo = "None", CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "", Name = "Darkseid", Status = 1, UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("7abbc069-155f-4399-a0fa-fb519b731824"), AlterEgo = "Eobard Thawne", CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "", Name = "Reverse Flash", Status = 1, UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("21ecf9ee-4fbd-4689-8251-2d6797c3acbe"), AlterEgo = "", CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "", Name = "Cicada", Status = 1, UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("d478bc91-5c51-4438-80bc-891f420a2d06"), AlterEgo = "", CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "", Name = "Prometheus", Status = 1, UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("65490a5b-bb49-4721-b442-90e39b64ceb6"), AlterEgo = "None", CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "", Name = "General Zodd", Status = 1, UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("2114c11d-fa71-4f95-8725-90bd699694cf"), AlterEgo = "Bruce Wayne", CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "", Name = "Batman", Status = 0, UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("cb0843de-7393-4686-88ea-4c6f80b12a47"), AlterEgo = "Clark Kent", CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "", Name = "Superman", Status = 0, UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("f5c868ae-da99-41ed-96a3-39a85e53fcb3"), AlterEgo = "Diana Prince", CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "", Name = "WonderWoman", Status = 0, UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("99201ef5-9e88-4f77-b2c9-d55bf844d1b2"), AlterEgo = "Barry Allen", CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "", Name = "The Flash", Status = 0, UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("0e4cb48e-fba4-48f1-925c-c396d49ee913"), AlterEgo = "Henry Allen", CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "", Name = "Jay Garrick", Status = 0, UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("442915a0-e192-4cd2-8800-eac1cd034383"), AlterEgo = "None", CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "", Name = "John Constantine", Status = 2, UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("4e9c9def-ca75-4ff2-8fa8-c20e0d4a734a"), AlterEgo = "", CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "", Name = "Deadpool", Status = 2, UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("20b23a0a-242f-4a0f-ad59-93ced35b3cce"), AlterEgo = "Hall Jordan", CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "", Name = "Green Lantern", Status = 0, UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("4746b9f8-ed25-4add-b99c-e4ad1d1e28c6"), AlterEgo = "Joh", CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "", Name = "Martian Manhunter", Status = 0, UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("7c19d2b9-d4cf-4182-988d-616b2f308518"), AlterEgo = "None", CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "Twisted duplicate of Superman created from a Duplication Ray By Lex On Earth", Name = "Bizarro", Status = 1, UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("b24205f9-43f7-4cf3-a422-1bfc01a1ef0f"), AlterEgo = "David Hyde", CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "Deep sea diver and would-be ocean conquero", Name = "Black Manta", Status = 1, UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("ed77765b-0b94-4cf5-bc49-0c6be4f628b6"), AlterEgo = "Vril dox", CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "Evil alien android", Name = "Brainiac", Status = 1, UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("15d336cc-5318-4031-b80d-680fb2161b9b"), AlterEgo = "Leonard Snart", CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "Blue-suited master of low temperatures", Name = "Captain Cold", Status = 1, UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("3a919c57-c6d4-419b-8d6a-6a0f8596ec14"), AlterEgo = "Priscilla Rich", CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "Cheetah suit-wearing woman", Name = "Cheetah", Status = 1, UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("5c04a440-45a6-4ba3-b31f-fc44777fd20e"), AlterEgo = "Doris Zeul", CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "Stole Apache Chief's magic powder to duplicate his powers", Name = "Giganta", Status = 1, UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("d8b9fd4f-d62f-4358-8cf3-a34e43812fa6"), AlterEgo = "Grodd", CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "Megalomaniacal exile from Gorilla City", Name = "Gorrilla Grodd", Status = 1, UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("cd36b2ef-1ad5-4e36-8968-7d263a7fdae3"), AlterEgo = "None", CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "Mad scientist and founder/leader of the Legion of Doom", Name = "Lex Luthor", Status = 1, UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("37480978-498e-49b0-bc8e-47ac2764b223"), AlterEgo = "Edward Nygma", CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "Megalomaniacal exile from Gorilla City", Name = "Riddler", Status = 1, UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("d2cd1117-1e96-41e2-9167-7291db001c56"), AlterEgo = "Thaal Sinestro", CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "Renegade ex-Green Lantern", Name = "Sinestro", Status = 1, UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) }
                    );
                });

            modelBuilder.Entity("Tour.Heroes.Api.Models.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreateAt");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<DateTimeOffset>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new { Id = new Guid("d8550cf0-3743-4afa-8530-49a85398cb49"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Name = "Justice League", UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("9ad1b2c3-5276-4b80-9995-ecb8bac1693b"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Name = "Legion of Doom", UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("b50e6562-7b62-4002-93a2-ef4e4f699318"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Name = "Avengers", UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 19, 10, 49, 1, 766, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) }
                    );
                });

            modelBuilder.Entity("Tour.Heroes.Api.Models.Entities.LinkEntities.MetaHumanAbility", b =>
                {
                    b.HasOne("Tour.Heroes.Api.Models.Entities.Ability", "Ability")
                        .WithMany("MetaHumanAbilities")
                        .HasForeignKey("AbilityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Tour.Heroes.Api.Models.Entities.MetaHuman", "MetaHuman")
                        .WithMany("MetaHumanAbilities")
                        .HasForeignKey("MetaHumanId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Tour.Heroes.Api.Models.Entities.LinkEntities.MetaHumanTeam", b =>
                {
                    b.HasOne("Tour.Heroes.Api.Models.Entities.MetaHuman", "MetaHuman")
                        .WithMany("MetaHumanTeams")
                        .HasForeignKey("MetaHumanId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Tour.Heroes.Api.Models.Entities.Team", "Team")
                        .WithMany("MetaHumanTeams")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
