// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tour.Heroes.Api;

namespace Tour.Heroes.Api.Migrations
{
    [DbContext(typeof(HeroDbContext))]
    [Migration("20190214144241_InitializeDatabase")]
    partial class InitializeDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Tour.Heroes.Api.Models.Entities.Ability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreateAt");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<DateTimeOffset>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Abilities");

                    b.HasData(
                        new { Id = new Guid("11165284-804b-4c0d-a883-7f4ff0591abf"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 451, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "Specialized in combat", Name = "Martial Arts", UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 451, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("c7070eff-84b5-48f5-afcf-52af20ad33ed"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 451, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "Speaks for itself", Name = "Super strength", UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 451, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("fe0b8931-219c-4403-bfda-0a84bca23780"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 451, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "Super fast for its opponent, but for it feels normal for the speedster", Name = "Super speed", UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 451, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("30de4a7c-33fe-4434-8aac-722824079ff0"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 451, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "Specialized with a sword", Name = "Swordsmaster", UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 451, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("be3cc731-8b26-422d-ae18-d0c0b80a1a0a"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 451, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "Speaks for itself", Name = "Marmot de graaf", UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 451, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("04ef9f14-88f2-498d-a9df-2bb917bef473"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 451, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "Super fast for its opponent, but for it feels normal for the speedster", Name = "harinak", UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 451, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("697715c6-2cce-4334-820f-e26a2a237f77"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 451, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "Specialized with a sword", Name = "haha", UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 451, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("434ad3d8-560b-4a29-91ca-617df5f31172"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 451, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "Overthrows his opponent with spells", Name = "Magic", UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 451, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) }
                    );
                });

            modelBuilder.Entity("Tour.Heroes.Api.Models.Entities.LinkEntities.MetaHumanAbility", b =>
                {
                    b.Property<Guid>("MetaHumanId");

                    b.Property<Guid>("AbilityId");

                    b.Property<DateTimeOffset>("CreateAt");

                    b.Property<DateTimeOffset>("UpdatedAt");

                    b.HasKey("MetaHumanId", "AbilityId");

                    b.HasIndex("AbilityId");

                    b.ToTable("MetahumansAbilities");

                    b.HasData(
                        new { MetaHumanId = new Guid("443abc75-d1bd-4389-b9ec-1a20f0e0e967"), AbilityId = new Guid("11165284-804b-4c0d-a883-7f4ff0591abf"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("52784edc-d956-4e02-b707-0deff12cf8e1"), AbilityId = new Guid("c7070eff-84b5-48f5-afcf-52af20ad33ed"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("da5554c5-d131-46bd-a1c7-8b00cf039301"), AbilityId = new Guid("30de4a7c-33fe-4434-8aac-722824079ff0"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("aa352f05-a919-4493-a993-30f34a719a19"), AbilityId = new Guid("fe0b8931-219c-4403-bfda-0a84bca23780"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("726bf5c2-3f49-49fb-8f4d-e70e39a36337"), AbilityId = new Guid("fe0b8931-219c-4403-bfda-0a84bca23780"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("da5554c5-d131-46bd-a1c7-8b00cf039301"), AbilityId = new Guid("be3cc731-8b26-422d-ae18-d0c0b80a1a0a"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("726bf5c2-3f49-49fb-8f4d-e70e39a36337"), AbilityId = new Guid("04ef9f14-88f2-498d-a9df-2bb917bef473"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("726bf5c2-3f49-49fb-8f4d-e70e39a36337"), AbilityId = new Guid("697715c6-2cce-4334-820f-e26a2a237f77"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("a6bb855f-995d-4142-8a13-3db335e4282d"), AbilityId = new Guid("be3cc731-8b26-422d-ae18-d0c0b80a1a0a"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("18cd6af9-a795-45b6-8b1b-d41aa6129506"), AbilityId = new Guid("c7070eff-84b5-48f5-afcf-52af20ad33ed"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("a22913e8-f3b2-431d-afd7-7519b270ec72"), AbilityId = new Guid("fe0b8931-219c-4403-bfda-0a84bca23780"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("18456bfd-6eb9-4e3b-93ab-bf0cc7bfa02b"), AbilityId = new Guid("11165284-804b-4c0d-a883-7f4ff0591abf"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("6ed9711c-bf30-407d-9249-5b1df86fda44"), AbilityId = new Guid("be3cc731-8b26-422d-ae18-d0c0b80a1a0a"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("1df18e4e-29e5-4cc9-8154-4f35075d3174"), AbilityId = new Guid("434ad3d8-560b-4a29-91ca-617df5f31172"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("bfecce09-fcd0-48f1-b910-4acafe105fcd"), AbilityId = new Guid("30de4a7c-33fe-4434-8aac-722824079ff0"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) }
                    );
                });

            modelBuilder.Entity("Tour.Heroes.Api.Models.Entities.LinkEntities.MetaHumanTeam", b =>
                {
                    b.Property<Guid>("MetaHumanId");

                    b.Property<Guid>("TeamId");

                    b.Property<DateTimeOffset>("CreateAt");

                    b.Property<DateTimeOffset>("UpdatedAt");

                    b.HasKey("MetaHumanId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("MetaHumanTeam");

                    b.HasData(
                        new { MetaHumanId = new Guid("a6bb855f-995d-4142-8a13-3db335e4282d"), TeamId = new Guid("a304e3f7-7cb7-4657-a7bf-4dac3bd7c822"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("18cd6af9-a795-45b6-8b1b-d41aa6129506"), TeamId = new Guid("a304e3f7-7cb7-4657-a7bf-4dac3bd7c822"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("a22913e8-f3b2-431d-afd7-7519b270ec72"), TeamId = new Guid("a304e3f7-7cb7-4657-a7bf-4dac3bd7c822"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("18456bfd-6eb9-4e3b-93ab-bf0cc7bfa02b"), TeamId = new Guid("a304e3f7-7cb7-4657-a7bf-4dac3bd7c822"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("a7ae6c62-b1c2-40c2-8e24-5892e39b2846"), TeamId = new Guid("a304e3f7-7cb7-4657-a7bf-4dac3bd7c822"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("dc17e228-11f7-40dd-bca2-9260847b852d"), TeamId = new Guid("a304e3f7-7cb7-4657-a7bf-4dac3bd7c822"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("eaee7287-5ed3-4106-9825-c8dcb992bdf4"), TeamId = new Guid("449e7ff9-27fe-4ce0-8d6f-f68e0a362912"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("a41576a7-93f4-4cb1-a75e-9e479313ab8e"), TeamId = new Guid("449e7ff9-27fe-4ce0-8d6f-f68e0a362912"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("d29f79d9-8c7d-43fc-9dea-4d9ab5ef843d"), TeamId = new Guid("449e7ff9-27fe-4ce0-8d6f-f68e0a362912"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("5c9ecda1-827b-4a8d-9735-9f795174cb3d"), TeamId = new Guid("449e7ff9-27fe-4ce0-8d6f-f68e0a362912"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("35f1235c-5d30-4629-af24-c09463399960"), TeamId = new Guid("449e7ff9-27fe-4ce0-8d6f-f68e0a362912"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("7f1b9c68-b577-468e-ab3a-abcc87fbb435"), TeamId = new Guid("449e7ff9-27fe-4ce0-8d6f-f68e0a362912"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("a92ac2b6-e7c1-409e-a7e0-b66b3c92a299"), TeamId = new Guid("449e7ff9-27fe-4ce0-8d6f-f68e0a362912"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("0aa12c57-0531-48bd-b982-528c0b21dbb9"), TeamId = new Guid("449e7ff9-27fe-4ce0-8d6f-f68e0a362912"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("546edb8d-36d8-41ac-81a7-cfb3aa2287c2"), TeamId = new Guid("449e7ff9-27fe-4ce0-8d6f-f68e0a362912"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { MetaHumanId = new Guid("49869c5e-1bfe-4607-9665-28a6c9658ef0"), TeamId = new Guid("449e7ff9-27fe-4ce0-8d6f-f68e0a362912"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) }
                    );
                });

            modelBuilder.Entity("Tour.Heroes.Api.Models.Entities.MetaHuman", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AlterEgo");

                    b.Property<DateTimeOffset>("CreateAt");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int>("Status");

                    b.Property<DateTimeOffset>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Metahumans");

                    b.HasData(
                        new { Id = new Guid("443abc75-d1bd-4389-b9ec-1a20f0e0e967"), AlterEgo = "", CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 451, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "", Name = "Deathstroke", Status = 1, UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 451, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("52784edc-d956-4e02-b707-0deff12cf8e1"), AlterEgo = "None", CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "", Name = "Darkseid", Status = 1, UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("da5554c5-d131-46bd-a1c7-8b00cf039301"), AlterEgo = "Eobard Thawne", CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "", Name = "Reverse Flash", Status = 1, UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("aa352f05-a919-4493-a993-30f34a719a19"), AlterEgo = "", CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "", Name = "Cicada", Status = 1, UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("726bf5c2-3f49-49fb-8f4d-e70e39a36337"), AlterEgo = "", CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "", Name = "Prometheus", Status = 1, UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("b51aa7aa-a68e-483f-937d-20f06fdfd3e7"), AlterEgo = "None", CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "", Name = "General Zodd", Status = 1, UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("a6bb855f-995d-4142-8a13-3db335e4282d"), AlterEgo = "Bruce Wayne", CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "", Name = "Batman", Status = 0, UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("18cd6af9-a795-45b6-8b1b-d41aa6129506"), AlterEgo = "Clark Kent", CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "", Name = "Superman", Status = 0, UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("a22913e8-f3b2-431d-afd7-7519b270ec72"), AlterEgo = "Diana Prince", CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "", Name = "WonderWoman", Status = 0, UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("18456bfd-6eb9-4e3b-93ab-bf0cc7bfa02b"), AlterEgo = "Barry Allen", CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "", Name = "The Flash", Status = 0, UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("6ed9711c-bf30-407d-9249-5b1df86fda44"), AlterEgo = "Henry Allen", CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "", Name = "Jay Garrick", Status = 0, UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("1df18e4e-29e5-4cc9-8154-4f35075d3174"), AlterEgo = "None", CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "", Name = "John Constantine", Status = 2, UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("bfecce09-fcd0-48f1-b910-4acafe105fcd"), AlterEgo = "", CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "", Name = "Deadpool", Status = 2, UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("a7ae6c62-b1c2-40c2-8e24-5892e39b2846"), AlterEgo = "Hall Jordan", CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "", Name = "Green Lantern", Status = 0, UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("dc17e228-11f7-40dd-bca2-9260847b852d"), AlterEgo = "Joh", CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "", Name = "Martian Manhunter", Status = 0, UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("eaee7287-5ed3-4106-9825-c8dcb992bdf4"), AlterEgo = "None", CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "Twisted duplicate of Superman created from a Duplication Ray By Lex On Earth", Name = "Bizarro", Status = 1, UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("a41576a7-93f4-4cb1-a75e-9e479313ab8e"), AlterEgo = "David Hyde", CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "Deep sea diver and would-be ocean conquero", Name = "Black Manta", Status = 1, UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("d29f79d9-8c7d-43fc-9dea-4d9ab5ef843d"), AlterEgo = "Vril dox", CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "Evil alien android", Name = "Brainiac", Status = 1, UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("5c9ecda1-827b-4a8d-9735-9f795174cb3d"), AlterEgo = "Leonard Snart", CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "Blue-suited master of low temperatures", Name = "Captain Cold", Status = 1, UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("35f1235c-5d30-4629-af24-c09463399960"), AlterEgo = "Priscilla Rich", CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "Cheetah suit-wearing woman", Name = "Cheetah", Status = 1, UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("7f1b9c68-b577-468e-ab3a-abcc87fbb435"), AlterEgo = "Doris Zeul", CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "Stole Apache Chief's magic powder to duplicate his powers", Name = "Giganta", Status = 1, UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("a92ac2b6-e7c1-409e-a7e0-b66b3c92a299"), AlterEgo = "Grodd", CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "Megalomaniacal exile from Gorilla City", Name = "Gorrilla Grodd", Status = 1, UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("0aa12c57-0531-48bd-b982-528c0b21dbb9"), AlterEgo = "None", CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "Mad scientist and founder/leader of the Legion of Doom", Name = "Lex Luthor", Status = 1, UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("546edb8d-36d8-41ac-81a7-cfb3aa2287c2"), AlterEgo = "Edward Nygma", CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "Megalomaniacal exile from Gorilla City", Name = "Riddler", Status = 1, UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("49869c5e-1bfe-4607-9665-28a6c9658ef0"), AlterEgo = "Thaal Sinestro", CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Description = "Renegade ex-Green Lantern", Name = "Sinestro", Status = 1, UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) }
                    );
                });

            modelBuilder.Entity("Tour.Heroes.Api.Models.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreateAt");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<DateTimeOffset>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Team");

                    b.HasData(
                        new { Id = new Guid("a304e3f7-7cb7-4657-a7bf-4dac3bd7c822"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Name = "Justice League", UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("449e7ff9-27fe-4ce0-8d6f-f68e0a362912"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Name = "Legion of Doom", UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                        new { Id = new Guid("cd0a17f0-b7e7-43d5-85c4-41218c56ddce"), CreateAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Name = "Avengers", UpdatedAt = new DateTimeOffset(new DateTime(2019, 2, 14, 14, 42, 41, 452, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) }
                    );
                });

            modelBuilder.Entity("Tour.Heroes.Api.Models.Entities.LinkEntities.MetaHumanAbility", b =>
                {
                    b.HasOne("Tour.Heroes.Api.Models.Entities.Ability", "Ability")
                        .WithMany("MetaHumanAbilities")
                        .HasForeignKey("AbilityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Tour.Heroes.Api.Models.Entities.MetaHuman", "MetaHuman")
                        .WithMany("MetaHumanAbilities")
                        .HasForeignKey("MetaHumanId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Tour.Heroes.Api.Models.Entities.LinkEntities.MetaHumanTeam", b =>
                {
                    b.HasOne("Tour.Heroes.Api.Models.Entities.MetaHuman", "MetaHuman")
                        .WithMany("MetaHumanTeams")
                        .HasForeignKey("MetaHumanId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Tour.Heroes.Api.Models.Entities.Team", "Team")
                        .WithMany("MetaHumanTeams")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
