// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tour.Heroes.Api;

namespace Tour.Heroes.Api.Migrations
{
    [DbContext(typeof(HeroDbContext))]
    partial class HeroDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Tour.Heroes.Api.Models.Ability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Abilities");

                    b.HasData(
                        new { Id = new Guid("e8d8f446-131f-456f-9031-0f36eec37d95"), Description = "Specialized in combat", Name = "Martial Arts" },
                        new { Id = new Guid("46cc7990-e44f-4b5d-9436-7c0b55b71f76"), Description = "Speaks for itself", Name = "Super strength" },
                        new { Id = new Guid("a2105d1e-7a93-4152-aa54-d7adcb7147b5"), Description = "Super fast for its opponent, but for it feels normal for the speedster", Name = "Super speed" },
                        new { Id = new Guid("79ee5b6d-bf67-4ce3-b315-bda73879a854"), Description = "Specialized with a sword", Name = "Swordsmaster" },
                        new { Id = new Guid("dbe15c06-3c00-48bd-9358-9a130408351d"), Description = "Speaks for itself", Name = "Marmot de graaf" },
                        new { Id = new Guid("5b1f4217-1b6c-4a5a-8090-9d88b5efcdc8"), Description = "Super fast for its opponent, but for it feels normal for the speedster", Name = "harinak" },
                        new { Id = new Guid("95d99eab-93f8-4eb4-bce8-a1296e757bc8"), Description = "Specialized with a sword", Name = "haha" }
                    );
                });

            modelBuilder.Entity("Tour.Heroes.Api.Models.Hero", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Heroes");

                    b.HasData(
                        new { Id = new Guid("170f3b78-7267-49ed-a44d-bce86ccb9d60"), Name = "Batman" },
                        new { Id = new Guid("708d8976-a5c8-4afa-bcb3-ba2d93f913e3"), Name = "Superman" },
                        new { Id = new Guid("f063751e-604e-42b5-b0bb-202fff920239"), Name = "WonderWoman" },
                        new { Id = new Guid("17cf5e2e-2417-412f-bf01-f66f978c5f68"), Name = "The Flash" },
                        new { Id = new Guid("2df360a7-8691-4316-8283-21b997a5d241"), Name = "Jay Garrick" }
                    );
                });

            modelBuilder.Entity("Tour.Heroes.Api.Models.HeroAbilities", b =>
                {
                    b.Property<Guid>("HeroId");

                    b.Property<Guid>("AbilityId");

                    b.HasKey("HeroId", "AbilityId");

                    b.HasIndex("AbilityId");

                    b.ToTable("HeroAbilities");

                    b.HasData(
                        new { HeroId = new Guid("170f3b78-7267-49ed-a44d-bce86ccb9d60"), AbilityId = new Guid("e8d8f446-131f-456f-9031-0f36eec37d95") },
                        new { HeroId = new Guid("708d8976-a5c8-4afa-bcb3-ba2d93f913e3"), AbilityId = new Guid("46cc7990-e44f-4b5d-9436-7c0b55b71f76") },
                        new { HeroId = new Guid("f063751e-604e-42b5-b0bb-202fff920239"), AbilityId = new Guid("79ee5b6d-bf67-4ce3-b315-bda73879a854") },
                        new { HeroId = new Guid("17cf5e2e-2417-412f-bf01-f66f978c5f68"), AbilityId = new Guid("a2105d1e-7a93-4152-aa54-d7adcb7147b5") },
                        new { HeroId = new Guid("2df360a7-8691-4316-8283-21b997a5d241"), AbilityId = new Guid("a2105d1e-7a93-4152-aa54-d7adcb7147b5") },
                        new { HeroId = new Guid("f063751e-604e-42b5-b0bb-202fff920239"), AbilityId = new Guid("dbe15c06-3c00-48bd-9358-9a130408351d") },
                        new { HeroId = new Guid("2df360a7-8691-4316-8283-21b997a5d241"), AbilityId = new Guid("5b1f4217-1b6c-4a5a-8090-9d88b5efcdc8") },
                        new { HeroId = new Guid("2df360a7-8691-4316-8283-21b997a5d241"), AbilityId = new Guid("95d99eab-93f8-4eb4-bce8-a1296e757bc8") }
                    );
                });

            modelBuilder.Entity("Tour.Heroes.Api.Models.HeroAbilities", b =>
                {
                    b.HasOne("Tour.Heroes.Api.Models.Ability", "Ability")
                        .WithMany("HeroesAbilities")
                        .HasForeignKey("AbilityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Tour.Heroes.Api.Models.Hero", "Hero")
                        .WithMany("AbilitiesHeroes")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
